cat /etc/filebeat/filebeat.yml
# ============================== Filebeat Inputs ===============================
filebeat.inputs:
- type: filestream
  id: nginx-logs
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
  parsers:
    - ndjson:
        target: ""
  processors:
    - dissect:
        tokenizer: '%{client.ip} - - [%{http.request.timestamp}] "%{http.host}" "%{http.request.method} %{http.request.path} HTTP/%{http.version}" %{http.response.status_code} %{http.response.bytes} "%{http.referrer}" "%{user_agent.original}" "%{other}"'
        field: "message"
        target_prefix: ""

# ======================= Elasticsearch Template Settings =======================
setup.template.enabled: false
setup.ilm.enabled: false
setup.template.name: "eos-logs"
setup.template.pattern: "eos-logs-*"

# ================================== Output ====================================
output.elasticsearch:
  hosts: ["172.16.11.76:9200"]
  index: "eos-logs-%{+yyyy.MM}"

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - drop_fields:
      fields: ["message"]
      ignore_missing: true

# ================================== Logging ===================================
logging.level: error
