
# ============================== Filebeat Inputs ===============================
filebeat.inputs:
- type: filestream
  id: nginx-logs
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log

# ======================= Elasticsearch Template Settings =======================
setup.template.enabled: false
setup.ilm.enabled: false
setup.template.name: "eos-logs"
setup.template.pattern: "eos-logs-*"

# ================================== Output ====================================
output.elasticsearch:
  hosts: ["172.16.11.76:9200"]
  index: "eos-logs-%{+yyyy.MM}"

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~

# ================================== Logging ===================================
logging.level: error
