filebeat.inputs:

# Get input from nginx
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
# Processors -> pharse the logs into seprate fields
    processors:
      - dissect:
          tokenizer: "%{nginx.client.ip} - %{nginx.user} [%{nginx.timestamp}] \"%{nginx.request.method} %{nginx.request.url} HTTP/%{nginx.request.http}\" %{nginx.response.status} %{nginx.bytes}"
          field: "message"
          target_prefix: "nginx"
      - add_fields:
          target: ''
          fields:
            service: nginx
            log_type: access
            
# Get input from HAProxy
  - type: log
    enabled: true
    paths:
      - /var/log/haproxy.log
# Processors -> pharse the logs into seprate fields
    processors:
      - dissect:
          tokenizer: "%{client.ip}:%{client.port} [%{haproxy.timestamp}] %{frontend} %{backend}/%{server} %{Tq}/%{Tw}/%{Tc}/%{Tr}/%{Tt} %{response.status} %{bytes} %{request_cookie} %{response_cookie} %{termination_state} %{actconn}/%{feconn}/%{beconn}/%{srv_conn}/%{retries} %{srv_queue}/%{backend_queue} \"%{request}\""
          field: "message"
          target_prefix: "haproxy"
      - add_fields:
          target: ''
          fields:
            service: haproxy
            log_type: access

# Output 
output.elasticsearch:
  hosts: ["http://localhost:9200"]

# Optional
setup.kibana:
  host: "http://localhost:5601"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
